### ISSUE TITLE
Issue with WPBakery Editor

### ISSUE THREAD

**Issue by shripal125** [middle-way-approach/gutenberg-typing-animation-block#3]
Hi,

I am trying to use the WordPress plugin on the Salient WP theme, It has WP Bakery as the editor, but the Gutenberg editor in WP Bakery is not working.

Can you please suggest on the same

**Comment by middle-way-approach** [comment]
Hi,

do other Gutenberg blocks work with the WPBakery editor?

I found this link https://kb.wpbakery.com/docs/faq/does-wpbakery-page-builder-works-with-the-gutenberg/

**Comment by shripal125** [comment]
Hi

Issue is resolved now, I updated my theme and WP Bakery version. Now its working . Thanks

Can u suggest how can I keep the animation on continous loop in gutenburg editor or via some settings?

**Comment by middle-way-approach** [comment]
Nice.

In the [sidebar](https://ps.w.org/typing-animation-block/assets/screenshot-1.png?rev=2211479) you can see the advanced options for loop (only on desktop). Set loop to true and loop count to 0.

**Comment by shripal125** [comment]
hi,

Not getting that option in wpbakery - gutenberg editor :(
![wpbakery-gutenberg](https://user-images.githubusercontent.com/18531187/74142942-e8b38e00-4c1f-11ea-9d62-f10f67b6c12e.png)

**Comment by shripal125** [comment]
![wpbakery-gutenberg](https://user-images.githubusercontent.com/18531187/74142981-f8cb6d80-4c1f-11ea-9d47-4699cdd55c24.png)

**Comment by middle-way-approach** [comment]
Hard to say. The Gutenberg editor usually shows a bar on the right side. Maybe it is closed by default. You can check if there is a way to open it otherwise I will open an issue to put some necessary control in the toolbar.

**Comment by shripal125** [comment]
i have checked all the options on the User Interface, but no luck.

Pls help

**Comment by middle-way-approach** [comment]
Can't help you quickly. I will put it as an issue and will make it accessible via the toolbar. But it will take time.
